# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

kde <- function(x, data, precision) {
    .Call(`_annodes_kde`, x, data, precision)
}

