# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cross_distance <- function(x, y, precision) {
    .Call(`_annodes_cross_distance`, x, y, precision)
}

penalty_function <- function(data, nodes, data_precision, node_precision) {
    .Call(`_annodes_penalty_function`, data, nodes, data_precision, node_precision)
}

